import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import NextAuthSessionProviders from "@/Providers/NextAuthSessionProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "OTT Platform",
  description: "Generated by ott platform app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthSessionProviders>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="bg-black text-white">
            <div className="container mx-auto">
              <Navbar />
              <div className="min-h-[70vh]">{children}</div>
              <Footer />
            </div>
          </div>
        </body>
      </NextAuthSessionProviders>
    </html>
  );
}
